import { JobSpecification } from "./Project";

export interface SpecificationManagerState {
    editingState: EditingState;
    autoGenerationState: AutoGenerationState;
    renderType: SpecificationRenderType;
}

export interface EditingState {
    editedSpecification?: JobSpecification;
    isEditModeOn: boolean;
    jsonValue?: string;
    jsonStringFromEditor?: string;
}

export interface AutoGenerationState {
    autoGeneratedSpecification?: JobSpecification;
    isAutoGenerationModeOn: boolean;
}


export enum SpecificationRenderType {
    UI = "UI",
    JSON = "JSON",
    // YAML = "YAML"
}